how/ui/urls.py
"""URLConf for how.ui"""

from django.contrib.auth import views as auth
from django.urls import path

from how.ui import views

# Create your URLConf here.
app_name = "ui"


auth_urls = [
    path("accounts/login/", auth.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth.LogoutView.as_view(), name="logout"),
    path("accounts/signup/", views.SignupView.as_view(), name="signup"),
    path("accounts/profile/", views.ProfileView.as_view(), name="profile"),
    path("accounts/<int:pk>/update/", views.UserUpdateView.as_view(), name="u-user"),
    path("accounts/<int:pk>/delete/", views.UserDeleteView.as_view(), name="d-user"),
    path(
        "accounts/password/change/",
        auth.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "accounts/password/change/done/",
        auth.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "accounts/password/reset/",
        auth.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "accounts/password/reset/done/",
        auth.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "accounts/password/reset/<uidb64>/<token>/",
        auth.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "accounts/password/reset/complete/",
        auth.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]


urlpatterns = auth_urls + [
    path(
        "learn/",
        views.LearnView.as_view(),
        name="learn",
    ),
    path(
        "learn/<slug:course>/",
        views.CourseDetailView.as_view(),
        name="course",
    ),
    path(
        "learn/<slug:course>/grades/",
        views.CourseGradesView.as_view(),
        name="grades",
    ),
    path(
        "learn/<slug:course>/grades/<slug:assignment>/",
        views.AssignmentDetailView.as_view(),
        name="assignment",
    ),
    path(
        "learn/<slug:course>/grades/<slug:assignment>/submit/",
        views.SubmissionCreateView.as_view(),
        name="submit",
    ),
    path(
        "learn/<slug:course>/grades/<slug:assignment>/submissions/<int:pk>/",
        views.SubmissionDetailView.as_view(),
        name="submission",
    ),
    path(
        "learn/<slug:course>/enroll/",
        views.EnrollmentCreateView.as_view(),
        name="enroll",
    ),
    path(
        "learn/<slug:course>/reviews/",
        views.CourseReviewsView.as_view(),
        name="reviews",
    ),
    path(
        "learn/<slug:course>/reviews/new/",
        views.ReviewCreateView.as_view(),
        name="new_review",
    ),
    path(
        "learn/<slug:course>/reviews/<int:pk>/",
        views.ReviewUpdateView.as_view(),
        name="update_review",
    ),
    path(
        "learn/<slug:course>/posts/",
        views.CoursePostsView.as_view(),
        name="posts",
    ),
    path(
        "learn/<slug:course>/posts/<slug:post>/",
        views.PostDetailView.as_view(),
        name="post",
    ),
    path(
        "learn/<slug:course>/<slug:module>/",
        views.ModuleDetailView.as_view(),
        name="module",
    ),
    path(
        "learn/<slug:course>/<slug:module>/<slug:lesson>/",
        views.LessonDetailView.as_view(),
        name="lesson",
    ),
    path(
        "learn/<slug:course>/<slug:module>/<slug:lesson>/<slug:item>/",
        views.ItemDetailView.as_view(),
        name="item",
    ),
]

how/ui/templates/ui/learn/posts/id.html
{% extends 'ui/learn/base.html' %}{% load i18n %}

<!---->
{% block title %}{{ block.super }} | {{ post.title }}{% endblock %}

<!---->
{% block styles %}{{ block.super }}
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/github-dark.min.css"
/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/highlight.min.js"></script>
<script>
  hljs.highlightAll();
</script>
<style>
  pre code.hljs {
    padding: 0;
    background-color: transparent;
  }
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.11/clipboard.min.js"></script>
{% endblock %}

<!---->
{% block breadcrumbs %}
<li>
  <a href="{% url 'ui:course' post.get_parent.slug %}">
    <i data-lucide="home" class="size-4"></i>
    <span>{% trans 'Home' %}</span>
  </a>
</li>
<li>
  <a href="{% url 'ui:posts' post.get_parent.slug %}">
    <i data-lucide="newspaper" class="size-4"></i>
    <span>{% trans 'Posts' %}</span>
  </a>
</li>
<li>
  <span>{{ post }}</span>
</li>
{% endblock %}

<!---->
{% block course_content %}
<div
  class="prose mx-auto prose-sm prose-video:rounded-box xl:prose-lg 2xl:prose-xl prose-headings:text-primary prose-headings:font-serif rtl:prose-headings:font-kufi prose-img:rounded-box prose-img:w-full prose-pre:bg-base-200 prose-pre:border prose-pre:border-base-300 prose-pre:bg-base-200 prose-pre:border prose-pre:border-base-300"
>
  <h1 class="text-primary text-2xl lg:text-4xl">{{ post.title }}</h1>
  {{ post.content }}
</div>
{% endblock %}

how/ui/templates/ui/learn/posts/list.html
{% extends 'ui/learn/base.html' %}{% load i18n %}

<!---->
{% block title %}{{ block.super }} | {% trans 'Grades' %}{% endblock %}

<!---->
{% block course_title %}{{ course }}{% endblock %}

<!---->
{% block breadcrumbs %}
<li>
  <a href="{% url 'ui:course' course.slug %}">
    <i data-lucide="home" class="size-4"></i>
    <span>{% trans 'Home' %}</span>
  </a>
</li>
<li>
  <span>
    <i data-lucide="newspaper" class="size-4"></i>
    <span>{% trans 'Posts' %}</span>
  </span>
</li>
{% endblock %}

<!---->
{% block course_content %}
<h2 class="text-primary text-2xl lg:text-4xl">{% trans 'Posts' %}</h2>

<ol class="grid grid-cols-12 gap-4">
  {% for post in posts %}
  <li class="col-span-12 md:col-span-6 lg:col-span-4 2xl:col-span-3">
    <article
      class="card card-sm bg-base-200 shadow-xs lg:card-md xl:card-lg 2xl:card-xl overflow-hidden"
    >
      <main class="card-body">
        <h2 class="card-title text-primary">{{ post.title }}</h2>

        <a
          href="{% url 'ui:post' course.slug post.slug %}"
          class="btn btn-sm btn-primary lg:btn-md xl:btn-lg 2xl:btn-xl font-semibold"
        >
          <span>{% trans 'Read' %}</span>

          <i
            data-lucide="chevron-right"
            class="size-4 md:size-6 xl:size-7 2xl:size-8 rtl:rotate-180"
          ></i>
        </a>
      </main>
    </article>
  </li>
  {% empty %}
  <li class="col-span-12">
    <article
      class="card card-sm bg-base-200 shadow-xs lg:card-md xl:card-lg 2xl:card-xl overflow-hidden"
    >
      <main class="card-body items-center">
        <i data-lucide="newspaper" class="mx-auto size-1/4 text-primary"></i>
        <h2 class="card-title text-primary">{% trans 'No posts' %}</h2>
        <p>
          {% trans 'Posts published by course instructor will appear here' %}
        </p>
      </main>
    </article>
  </li>
  {% endfor %}
</ol>
{% endblock %}