how/ui/urls.py
"""URLConf for how.ui"""

from django.contrib.auth import views as auth
from django.urls import path

from how.ui import views

# Create your URLConf here.
app_name = "ui"


auth_urls = [
    path("accounts/login/", auth.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth.LogoutView.as_view(), name="logout"),
    path("accounts/signup/", views.SignupView.as_view(), name="signup"),
    path("accounts/profile/", views.ProfileView.as_view(), name="profile"),
    path("accounts/<int:pk>/update/", views.UserUpdateView.as_view(), name="u-user"),
    path("accounts/<int:pk>/delete/", views.UserDeleteView.as_view(), name="d-user"),
    path(
        "accounts/password/change/",
        auth.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "accounts/password/change/done/",
        auth.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "accounts/password/reset/",
        auth.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "accounts/password/reset/done/",
        auth.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "accounts/password/reset/<uidb64>/<token>/",
        auth.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "accounts/password/reset/complete/",
        auth.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]


urlpatterns = auth_urls + [
    path(
        "learn/",
        views.LearnView.as_view(),
        name="learn",
    ),
    path(
        "learn/<slug:course>/",
        views.CourseDetailView.as_view(),
        name="course",
    ),
    path(
        "learn/<slug:course>/grades/",
        views.CourseGradesView.as_view(),
        name="grades",
    ),
    path(
        "learn/<slug:course>/grades/<slug:assignment>/",
        views.AssignmentDetailView.as_view(),
        name="assignment",
    ),
    path(
        "learn/<slug:course>/grades/<slug:assignment>/submit/",
        views.SubmissionCreateView.as_view(),
        name="submit",
    ),
    path(
        "learn/<slug:course>/grades/<slug:assignment>/submissions/<int:pk>/",
        views.SubmissionDetailView.as_view(),
        name="submission",
    ),
    path(
        "learn/<slug:course>/enroll/",
        views.EnrollmentCreateView.as_view(),
        name="enroll",
    ),
    path(
        "learn/<slug:course>/reviews/",
        views.CourseReviewsView.as_view(),
        name="reviews",
    ),
    path(
        "learn/<slug:course>/reviews/new/",
        views.ReviewCreateView.as_view(),
        name="new_review",
    ),
    path(
        "learn/<slug:course>/reviews/<int:pk>/",
        views.ReviewUpdateView.as_view(),
        name="update_review",
    ),
    path(
        "learn/<slug:course>/posts/",
        views.CoursePostsView.as_view(),
        name="posts",
    ),
    path(
        "learn/<slug:course>/posts/<slug:post>/",
        views.PostDetailView.as_view(),
        name="post",
    ),
    path(
        "learn/<slug:course>/<slug:module>/",
        views.ModuleDetailView.as_view(),
        name="module",
    ),
    path(
        "learn/<slug:course>/<slug:module>/<slug:lesson>/",
        views.LessonDetailView.as_view(),
        name="lesson",
    ),
    path(
        "learn/<slug:course>/<slug:module>/<slug:lesson>/<slug:item>/",
        views.ItemDetailView.as_view(),
        name="item",
    ),
]

how/ui/templates/ui/courses/id.html
{% extends 'ui/base.html' %}{% load i18n wagtailcore_tags wagtailimages_tags %}

<!---->
{% block title %}{{ block.super }}{{ course.title }}{% endblock %}

<!---->
{% block meta %}
<meta
  name="description"
  content="{% trans 'House Of Wisdom' %} | {{ course.title }}"
/>
<meta property="og:url" content="{{ request.build_absolute_uri }}" />
<meta property="og:type" content="website" />
<meta
  property="og:title"
  content="{% trans 'House Of Wisdom' %} | {{ course.title }}"
/>
<meta
  property="og:description"
  content="{% trans 'House Of Wisdom' %} | {{ course.title }}"
/>
<meta property="og:image" content="{{ course.image.file.url }}" />
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="630" />

<meta name="twitter:card" content="summary_large_image" />
<meta property="twitter:domain" content="{{ request.build_absolute_uri }}" />
<meta property="twitter:url" content="{{ request.build_absolute_uri }}" />
<meta
  name="twitter:title"
  content="{% trans 'House Of Wisdom' %} | {{ course.title }}"
/>
<meta
  name="twitter:description"
  content="{% trans 'House Of Wisdom' %} | {{ course.title }}"
/>
<meta name="twitter:image" content="{{ course.image.file.url }}" />
{% endblock %}

<!---->
{% block content %}
<div class="container mx-auto px-4 py-20">
  <nav class="breadcrumbs text-xs lg:text-sm">
    <ol>
      {% for page in course.get_ancestors %}{% if not page.is_root %}
      <li>
        <a href="{% pageurl page %}"> {{ page }} </a>
      </li>
      {% endif %}{% endfor %}
      <li>{{ page }}</li>
    </ol>
  </nav>

  <section class="grid gap-8">
    <div
      class="hero relative bg-gradient-to-r from-sky-400 via-blue-500 to-indigo-700 rounded-box md:aspect-video"
    >
      <div class="hero-content grid gap-8">
        <h1 class="text-2xl text-primary font-black md:text-3xl lg:text-7xl">
          {{ course.title }}
        </h1>

        {% if course in request.user.courses.all %}
        <a
          href="{% url 'ui:course' course.slug %}"
          class="btn glass btn-primary lg:btn-lg 2xl:btn-xl"
        >
          {% trans 'Go to course' %}
        </a>
        {% else %}
        <form
          action="{% url 'ui:enroll' course.slug %}"
          method="post"
        >
          {% csrf_token %}

          <button class="btn glass btn-primary lg:btn-lg 2xl:btn-xl">
            {% trans 'Enroll now' %}
          </button>
        </form>
        {% endif %}
      </div>
    </div>

    <div
      class="prose mx-auto text-inherit prose-sm lg:prose prose-video:rounded-box xl:prose-lg 2xl:prose-xl prose-headings:text-primary prose-headings:font-serif rtl:prose-headings:font-kufi prose-img:rounded-box prose-img:w-full prose-pre:bg-base-200 prose-pre:border prose-pre:border-base-300"
    >
      {% image course.image fill-1920x1080 %}

      <h2>{{ course.headline }}</h2>
      {{ course.description|richtext }}

      <h3>{% trans 'Prerequisites' %}</h3>
      {{ course.prerequisites|richtext }}

      <h3>{% trans 'Skills you will gain' %}</h3>
      <div class="flex flex-wrap items-center gap-4">
        {% for skill in course.skills.all %}
        <span
          class="badge {% cycle 'badge-primary' 'badge-secondary' 'badge-success' 'badge-info' 'badge-warning' 'badge-error' %}"
        >
          {{ skill }}
        </span>
        {% endfor %}
      </div>

      <h3>
        {{ course.get_module_count }} {% trans 'modules are in this course' %}
      </h3>
      <div class="grid gap-4">
        {% for module in course.get_modules.specific %}
        <div class="collapse collapse-arrow bg-base-200 rounded-box shadow-xs">
          <input id="module-{{ module.id }}" type="checkbox" class="hidden" />

          <label for="module-{{ module.id }}" class="collapse-title">
            {{ module.title }}
          </label>

          <div class="collapse-content">
            <div>{{ module.description|richtext }}</div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
</div>
{% endblock %}