how/ui/urls.py
"""URLConf for how.ui"""

from django.contrib.auth import views as auth
from django.urls import path

from how.ui import views

# Create your URLConf here.
app_name = "ui"


auth_urls = [
    path("accounts/login/", auth.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth.LogoutView.as_view(), name="logout"),
    path("accounts/signup/", views.SignupView.as_view(), name="signup"),
    path("accounts/profile/", views.ProfileView.as_view(), name="profile"),
    path("accounts/<int:pk>/update/", views.UserUpdateView.as_view(), name="u-user"),
    path("accounts/<int:pk>/delete/", views.UserDeleteView.as_view(), name="d-user"),
    path(
        "accounts/password/change/",
        auth.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "accounts/password/change/done/",
        auth.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "accounts/password/reset/",
        auth.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "accounts/password/reset/done/",
        auth.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "accounts/password/reset/<uidb64>/<token>/",
        auth.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "accounts/password/reset/complete/",
        auth.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]


urlpatterns = auth_urls + [
    path(
        "learn/",
        views.LearnView.as_view(),
        name="learn",
    ),
    path(
        "learn/<slug:course>/",
        views.CourseDetailView.as_view(),
        name="course",
    ),
    path(
        "learn/<slug:course>/grades/",
        views.CourseGradesView.as_view(),
        name="grades",
    ),
    path(
        "learn/<slug:course>/grades/<slug:assignment>/",
        views.AssignmentDetailView.as_view(),
        name="assignment",
    ),
    path(
        "learn/<slug:course>/grades/<slug:assignment>/submit/",
        views.SubmissionCreateView.as_view(),
        name="submit",
    ),
    path(
        "learn/<slug:course>/grades/<slug:assignment>/submissions/<int:pk>/",
        views.SubmissionDetailView.as_view(),
        name="submission",
    ),
    path(
        "learn/<slug:course>/enroll/",
        views.EnrollmentCreateView.as_view(),
        name="enroll",
    ),
    path(
        "learn/<slug:course>/reviews/",
        views.CourseReviewsView.as_view(),
        name="reviews",
    ),
    path(
        "learn/<slug:course>/reviews/new/",
        views.ReviewCreateView.as_view(),
        name="new_review",
    ),
    path(
        "learn/<slug:course>/reviews/<int:pk>/",
        views.ReviewUpdateView.as_view(),
        name="update_review",
    ),
    path(
        "learn/<slug:course>/posts/",
        views.CoursePostsView.as_view(),
        name="posts",
    ),
    path(
        "learn/<slug:course>/posts/<slug:post>/",
        views.PostDetailView.as_view(),
        name="post",
    ),
    path(
        "learn/<slug:course>/<slug:module>/",
        views.ModuleDetailView.as_view(),
        name="module",
    ),
    path(
        "learn/<slug:course>/<slug:module>/<slug:lesson>/",
        views.LessonDetailView.as_view(),
        name="lesson",
    ),
    path(
        "learn/<slug:course>/<slug:module>/<slug:lesson>/<slug:item>/",
        views.ItemDetailView.as_view(),
        name="item",
    ),
]

how/ui/templates/ui/learn/base.html
{% extends 'ui/base.html' %}{% load i18n wagtailcore_tags wagtailimages_tags %}

<!---->
{% block title %}{{ block.super }} | {% trans 'Learn' %} | {{ course.title }}{% endblock %}

<!---->
{% block navbar %}{% endblock %}

<!---->
{% block content %}
<div
  id="course-container"
  class="drawer bg-base-200 lg:drawer-open size-full overflow-hidden lg:max-h-[calc(100dvh-1rem-2px)]"
>
  <input id="course-drawer" type="checkbox" class="drawer-toggle" />

  <section
    class="drawer-content relative size-full max-w-[calc(100dvw-0.5rem)] max-h-[calc(100dvh-0.5rem)] lg:max-h-[calc(100dvh-1rem)] lg:max-w-[calc(100dvw-1rem)]"
  >
    <header
      class="rounded-b-field rounded-t-box absolute inset-x-0 top-0 z-10 px-2 backdrop-blur-3xl lg:px-4"
    >
      <nav class="navbar p-0">
        <div class="navbar-start gap-4">
          <div
            id="btn-toggle"
            class="hidden tooltip tooltip-right rtl:tooltip-left tooltip-primary"
            data-tip="{% trans 'Open drawer' %}"
          >
            <button
              onclick="toggleDrawer()"
              aria-label="close sidebar"
              class="btn btn-square btn-soft btn-sm btn-primary md:btn-md 2xl:btn-lg"
            >
              <i
                data-lucide="menu"
                class="size-4 md:size-6 xl:size-7 2xl:size-8"
              ></i>
              <span class="sr-only">{% trans 'Open drawer' %}</span>
            </button>
          </div>

          <div
            class="tooltip tooltip-right rtl:tooltip-left tooltip-primary lg:hidden"
            data-tip="{% trans 'Open drawer' %}"
          >
            <label
              for="course-drawer"
              aria-label="close sidebar"
              class="btn btn-square btn-soft btn-sm btn-primary md:btn-md 2xl:btn-lg"
            >
              <i
                data-lucide="menu"
                class="size-4 md:size-6 xl:size-7 2xl:size-8"
              ></i>
              <span class="sr-only">{% trans 'Open drawer' %}</span>
            </label>
          </div>

          <h1
            id="course-title"
            class="text-primary font-bold text-xl lg:hidden"
          >
            {% block course_title %}{{ course }}{% endblock %}
          </h1>
        </div>

        <div class="navbar-end gap-2">
          <div
            class="tooltip tooltip-left rtl:tooltip-right tooltip-primary"
            data-tip="Search"
          >
            <button
              class="btn btn-square btn-soft btn-sm btn-primary md:btn-md 2xl:btn-lg"
            >
              <i
                data-lucide="search"
                class="size-4 md:size-6 xl:size-7 2xl:size-8"
              ></i>
              <span class="sr-only">Search</span>
            </button>
          </div>

          <div
            class="tooltip tooltip-left rtl:tooltip-right tooltip-success"
            data-tip="{% trans 'Al-Wazeer' %}"
          >
            <label
              for="chat-drawer"
              class="btn btn-square btn-soft btn-sm btn-success md:btn-md 2xl:btn-lg"
            >
              <i
                data-lucide="brain-circuit"
                class="size-4 md:size-6 xl:size-7 2xl:size-8"
              ></i>
              <span class="sr-only">{% trans 'Al-Wazeer' %}</span>
            </label>
          </div>
        </div>
      </nav>
    </header>

    <div
      class="rounded-box bg-base-100 size-full overflow-y-auto max-h-[calc(100dvh-0.5rem)] lg:max-h-[calc(100dvh-1rem)]"
    >
      <main class="container grid gap-8 px-4 py-16 lg:mx-auto">
        <div class="breadcrumbs text-primary text-xs lg:text-sm">
          <ol>
            {% block breadcrumbs %}{% endblock %}
          </ol>
        </div>

        {% block course_content %}
        <figure class="skeleton overflow-clip md:aspect-video">
          {% image course.image scale-100 %}
        </figure>

        <div
          class="prose mx-auto prose-sm prose-video:rounded-box xl:prose-lg 2xl:prose-xl prose-headings:text-primary prose-headings:font-serif rtl:prose-headings:font-kufi prose-img:rounded-box prose-img:w-full prose-pre:bg-base-200 prose-pre:border prose-pre:border-base-300"
        >
          <h1>{% trans 'Welcome to' %} {{ course.title }}</h1>
          {{ course.description|richtext }}

          <h2>{% trans 'Prerequisites' %}</h2>
          {{ course.prerequisites|richtext }}
        </div>
        {% endblock %}
      </main>
    </div>
  </section>

  <section
    class="drawer-side md:min-w-xs lg:min-w-sm z-50 lg:z-20 lg:max-h-[calc(100dvh-1rem)]"
  >
    <label
      for="course-drawer"
      aria-label="close sidebar"
      class="drawer-overlay lg:hidden"
    ></label>

    <section
      class="rounded-box lg:bg-base-200 bg-base-100/50 flex size-full max-w-[calc(100dvw-0.5rem)] flex-col justify-between overflow-hidden overflow-y-auto backdrop-blur-3xl sm:w-10/12 md:w-8/12 lg:w-full"
    >
      <div class="flex h-full flex-col">
        <header class="flex items-center justify-between gap-4 p-4">
          <div class="flex items-center gap-2">
            <div
              class="tooltip tooltip-right rtl:tooltip-left tooltip-primary aspect-square sm:hidden"
              data-tip="{% trans 'Open drawer' %}"
            >
              <label
                for="nav-drawer"
                aria-label="{% trans 'close sidebar' %}"
                class="btn btn-square btn-soft btn-sm btn-primary md:btn-md 2xl:btn-lg"
              >
                <i
                  data-lucide="menu"
                  class="size-4 md:size-6 xl:size-7 2xl:size-8"
                ></i>
                <span class="sr-only">{% trans 'Open drawer' %}</span>
              </label>
            </div>
            {% block drawer_actions %}{% endblock %}

            <h1 class="text-primary text-xl font-bold lg:text-2xl">
              {% block drawer_title %}{{ course.title }}{% endblock %}
            </h1>
          </div>

          <div
            class="hidden tooltip tooltip-left rtl:tooltip-right hover:tooltip-error lg:block"
            data-tip="{% trans 'Close' %}"
          >
            <button
              aria-label="close sidebar"
              onclick="toggleDrawer()"
              class="btn btn-square btn-soft btn-sm btn-primary hover:btn-error md:btn-md 2xl:btn-lg"
            >
              <i
                data-lucide="x"
                class="size-4 md:size-6 xl:size-7 2xl:size-8"
              ></i>
              <span class="sr-only">{% trans 'Close' %}</span>
            </button>
          </div>

          <div
            class="tooltip tooltip-left rtl:tooltip-right hover:tooltip-error lg:hidden"
            data-tip="{% trans 'Close' %}"
          >
            <label
              for="course-drawer"
              aria-label="close sidebar"
              class="btn btn-square btn-soft btn-sm btn-primary hover:btn-error md:btn-md 2xl:btn-lg"
            >
              <i
                data-lucide="x"
                class="size-4 md:size-6 xl:size-7 2xl:size-8"
              ></i>
              <span class="sr-only">{% trans 'Close' %}</span>
            </label>
          </div>
        </header>

        <ol class="flex size-full grow flex-col gap-4 overflow-y-auto px-4">
          {% block drawer_content %}
          <li>
            <a
              href="{% url 'ui:course' course.slug %}"
              class="btn btn-sm btn-ghost btn-primary md:btn-md btn-block 2xl:btn-xl justify-start"
            >
              <i
                data-lucide="home"
                class="size-4 md:size-6 xl:size-7 2xl:size-8"
              ></i>
              <span>{% trans 'Home' %}</span>
            </a>
          </li>
          <li>
            <div class="rounded-field collapse w-full">
              <input
                id="modules"
                type="checkbox"
                name="modules"
                class="hidden"
              />

              <label
                for="modules"
                class="collapse-title btn btn-sm btn-ghost btn-primary md:btn-md btn-block 2xl:btn-xl justify-between p-4"
              >
                <span class="flex items-center gap-[inherit]">
                  <i
                    data-lucide="book-text"
                    class="size-4 md:size-6 xl:size-7 2xl:size-8"
                  ></i>
                  <span>{% trans 'Course Material' %}</span>
                </span>

                <i
                  data-lucide="chevron-down"
                  class="size-4 md:size-6 xl:size-7 2xl:size-8"
                ></i>
              </label>

              <div class="collapse-content">
                <ol class="grid gap-2">
                  {% for module in modules %}
                  <li>
                    <a
                      href="{% url 'ui:module' course.slug module.slug %}"
                      class="btn btn-sm btn-ghost btn-primary md:btn-md btn-block 2xl:btn-xl justify-between"
                    >
                      <span class="flex items-center gap-4">
                        <span class="badge badge-xs badge-success lg:badge-sm"
                          >{{ forloop.counter }}</span
                        >
                        <span>{{ module }}</span>
                      </span>

                      <i
                        data-lucide="chevron-right"
                        class="size-4 md:size-6 xl:size-7 2xl:size-8 rtl:rotate-180"
                      ></i>
                    </a>
                  </li>
                  {% endfor %}
                </ol>
              </div>
            </div>
          </li>
          <li>
            <a
              href="{% url 'ui:grades' course.slug %}"
              class="btn btn-sm btn-ghost btn-primary md:btn-md btn-block 2xl:btn-xl justify-start"
            >
              <i
                data-lucide="book-check"
                class="size-4 md:size-6 xl:size-7 2xl:size-8"
              ></i>
              <span>{% trans 'Grades' %}</span>
            </a>
          </li>
          <li>
            <a
              href="{% url 'ui:posts' course.slug %}"
              class="btn btn-sm btn-ghost btn-primary md:btn-md btn-block 2xl:btn-xl justify-start"
            >
              <i
                data-lucide="newspaper"
                class="size-4 md:size-6 xl:size-7 2xl:size-8"
              ></i>
              <span>{% trans 'Posts' %}</span>
            </a>
          </li>
          <li>
            <a
              href="{% url 'ui:new_review' course.slug %}"
              class="btn btn-sm btn-ghost btn-primary md:btn-md btn-block 2xl:btn-xl justify-start"
            >
              <i
                data-lucide="stars"
                class="size-4 md:size-6 xl:size-7 2xl:size-8"
              ></i>
              <span>{% trans 'Rate this course' %}</span>
            </a>
          </li>
          {% endblock %}
        </ol>
      </div>
    </section>
  </section>
</div>

<script>
  const toggleDrawer = () => {
    document
      .getElementById("course-container")
      .classList.toggle("lg:drawer-open");
    document.getElementById("course-title").classList.toggle("lg:hidden");
    document.getElementById("btn-toggle").classList.toggle("hidden");
  };
</script>
{% endblock %}

how/ui/templates/ui/learn/index.html
{% extends 'ui/base.html' %}{% load i18n wagtailcore_tags wagtailimages_tags %}

<!---->
{% block title %}{{ block.super }} | {% trans 'Learn' %}{% endblock %}

<!---->
{% block content %}
<main class="container mx-auto grid gap-8 px-4 py-20">
  <div
    class="hero relative bg-gradient-to-r from-indigo-500 from-10% via-sky-500 via-50% to-emerald-500 to-90% rounded-box md:aspect-video"
  >
    <div class="hero-content flex flex-col gap-8">
      <h1 class="text-3xl text-primary font-black lg:text-7xl">
        {% trans 'My Learning' %}
      </h1>
    </div>
  </div>

  <section class="tabs tabs-border">
    <input
      type="radio"
      name="content"
      class="tab text-primary"
      aria-label="{% trans 'In Progress' %}"
      checked
    />
    <div class="tab-content pt-4">
      <ol class="grid grid-cols-12 gap-4">
        {% for item in courses %}
        <li class="col-span-12 md:col-span-6 lg:col-span-4 2xl:col-span-3">
          <article
            class="card card-sm bg-base-200 shadow-xs lg:card-md xl:card-lg 2xl:card-xl overflow-hidden"
          >
            <main class="card-body gap-4">
              <h2 class="card-title text-primary">{{ item.course.title }}</h2>

              <p>{{ item.course.headline }}</p>

              <div
                class="tooltip tooltip-bottom tooltip-success"
                data-tip="{% trans 'Progress' %} {{ item.progress }}"
              >
                <progress
                  value="{{ item.progress }}"
                  class="progress progress-success"
                ></progress>
              </div>

              <a
                href="{% url 'ui:course' item.course.slug %}"
                class="btn btn-sm btn-primary lg:btn-md xl:btn-lg 2xl:btn-xl font-semibold"
              >
                <span>{% trans 'Go to course' %}</span>

                <i
                  data-lucide="chevron-right"
                  class="size-4 md:size-6 xl:size-7 2xl:size-8 rtl:rotate-180"
                ></i>
              </a>
            </main>
          </article>
        </li>
        {% empty %}
        <li class="col-span-12">
          <article
            class="card card-sm bg-base-200 shadow-xs lg:card-md xl:card-lg 2xl:card-xl overflow-hidden"
          >
            <main class="card-body items-center">
              <i data-lucide="book" class="mx-auto size-1/4 text-primary"></i>
              <h2 class="card-title text-primary">{% trans 'No courses' %}</h2>
              <p>
                {% trans 'Your courses will appear here after enrollment' %}
              </p>
            </main>
          </article>
        </li>
        {% endfor %}
      </ol>
    </div>

    <input
      type="radio"
      name="content"
      class="tab text-success"
      aria-label="{% trans 'Completed' %}"
    />
    <div class="tab-content pt-4">
      <ol class="grid grid-cols-12 gap-4">
        {% for item in completed_courses %}
        <li class="col-span-12 md:col-span-6 lg:col-span-4 2xl:col-span-3">
          <article
            class="card card-sm bg-base-200 shadow-xs lg:card-md xl:card-lg 2xl:card-xl overflow-hidden"
          >
            <main class="card-body gap-4">
              <h1 class="card-title text-primary">{{ item.course.title }}</h1>

              <p>{{ item.course.headline }}</p>

              <div
                class="tooltip tooltip-bottom tooltip-success"
                data-tip="{% trans 'Progress' %} {{ item.progress }}"
              >
                <progress
                  value="{{ item.progress }}"
                  class="progress progress-success"
                ></progress>
              </div>

              <a
                href="{% url 'ui:course' course.slug %}"
                class="btn btn-sm btn-primary lg:btn-md xl:btn-lg 2xl:btn-xl font-semibold"
              >
                <span>{% trans 'Go to course' %}</span>

                <i
                  data-lucide="chevron-right"
                  class="size-4 md:size-6 xl:size-7 2xl:size-8 rtl:rotate-180"
                ></i>
              </a>
            </main>
          </article>
        </li>
        {% empty %}
        <li class="col-span-12">
          <article
            class="card card-sm bg-base-200 shadow-xs lg:card-md xl:card-lg 2xl:card-xl overflow-hidden"
          >
            <main class="card-body items-center">
              <i
                data-lucide="book-check"
                class="mx-auto size-1/4 text-primary"
              ></i>
              <h2 class="card-title text-primary">
                {% trans 'No completed courses' %}
              </h2>
              <p>{% trans 'Your completed courses will appear here' %}</p>
            </main>
          </article>
        </li>
        {% endfor %}
      </ol>
    </div>
  </section>
</main>
{% endblock %}