how/ui/urls.py
"""URLConf for how.ui"""

from django.contrib.auth import views as auth
from django.urls import path

from how.ui import views

# Create your URLConf here.
app_name = "ui"


auth_urls = [
    path("accounts/login/", auth.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth.LogoutView.as_view(), name="logout"),
    path("accounts/signup/", views.SignupView.as_view(), name="signup"),
    path("accounts/profile/", views.ProfileView.as_view(), name="profile"),
    path("accounts/<int:pk>/update/", views.UserUpdateView.as_view(), name="u-user"),
    path("accounts/<int:pk>/delete/", views.UserDeleteView.as_view(), name="d-user"),
    path(
        "accounts/password/change/",
        auth.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "accounts/password/change/done/",
        auth.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "accounts/password/reset/",
        auth.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "accounts/password/reset/done/",
        auth.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "accounts/password/reset/<uidb64>/<token>/",
        auth.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "accounts/password/reset/complete/",
        auth.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]


urlpatterns = auth_urls + [
    path(
        "learn/",
        views.LearnView.as_view(),
        name="learn",
    ),
    path(
        "learn/<slug:course>/",
        views.CourseDetailView.as_view(),
        name="course",
    ),
    path(
        "learn/<slug:course>/grades/",
        views.CourseGradesView.as_view(),
        name="grades",
    ),
    path(
        "learn/<slug:course>/grades/<slug:assignment>/",
        views.AssignmentDetailView.as_view(),
        name="assignment",
    ),
    path(
        "learn/<slug:course>/grades/<slug:assignment>/submit/",
        views.SubmissionCreateView.as_view(),
        name="submit",
    ),
    path(
        "learn/<slug:course>/grades/<slug:assignment>/submissions/<int:pk>/",
        views.SubmissionDetailView.as_view(),
        name="submission",
    ),
    path(
        "learn/<slug:course>/enroll/",
        views.EnrollmentCreateView.as_view(),
        name="enroll",
    ),
    path(
        "learn/<slug:course>/reviews/",
        views.CourseReviewsView.as_view(),
        name="reviews",
    ),
    path(
        "learn/<slug:course>/reviews/new/",
        views.ReviewCreateView.as_view(),
        name="new_review",
    ),
    path(
        "learn/<slug:course>/reviews/<int:pk>/",
        views.ReviewUpdateView.as_view(),
        name="update_review",
    ),
    path(
        "learn/<slug:course>/posts/",
        views.CoursePostsView.as_view(),
        name="posts",
    ),
    path(
        "learn/<slug:course>/posts/<slug:post>/",
        views.PostDetailView.as_view(),
        name="post",
    ),
    path(
        "learn/<slug:course>/<slug:module>/",
        views.ModuleDetailView.as_view(),
        name="module",
    ),
    path(
        "learn/<slug:course>/<slug:module>/<slug:lesson>/",
        views.LessonDetailView.as_view(),
        name="lesson",
    ),
    path(
        "learn/<slug:course>/<slug:module>/<slug:lesson>/<slug:item>/",
        views.ItemDetailView.as_view(),
        name="item",
    ),
]

how/ui/templates/ui/learn/content/grades.html
{% extends 'ui/learn/base.html' %}{% load i18n wagtailcore_tags %}

<!---->
{% block title %}{{ block.super }} | {% trans 'Grades' %}{% endblock %}

<!---->
{% block course_title %}{{ course }}{% endblock %}

<!---->
{% block breadcrumbs %}
<li>
  <a href="{% url 'ui:course' course.slug %}">
    <i data-lucide="home" class="size-4"></i>
    <span>{% trans 'Home' %}</span>
  </a>
</li>
<li>
  <span>
    <i data-lucide="book-check" class="size-4"></i>
    <span>{% trans 'Grades' %}</span>
  </span>
</li>
{% endblock %}

<!---->
{% block course_content %}
<h2 class="text-primary text-2xl lg:text-4xl">{% trans 'Grades' %}</h2>

<div
  class="overflow-x-auto rounded-box border border-base-content/5 bg-base-200"
>
  <table class="table">
    <thead class="text-primary">
      <tr>
        <th>{% trans 'Assignment' %}</th>
        <th>{% trans 'Minimum' %}</th>
      </tr>
    </thead>
    <tbody>
      {% for assignment in assignments %}
      <tr>
        <td>
          <a
            href="{% url 'ui:assignment' course.slug assignment.slug %}"
            class="link link-primary font-bold"
          >
            {{ assignment }}
          </a>
        </td>
        <td>%{{ assignment.min_percentage }}</td>
      </tr>
      {% empty %}
      <tr>
        <th colspan="4">{% trans 'No assignments in this course' %}</th>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

how/ui/templates/ui/learn/content/item.html
{% extends 'ui/learn/content/lesson.html' %}{% load i18n %}

<!---->
{% block title %}{{ block.super }} | {{ item.title }}{% endblock %}

<!---->
{% block styles %}{{ block.super }}
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/github-dark.min.css"
/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/highlight.min.js"></script>
<script>
  hljs.highlightAll();
</script>
<style>
  pre code.hljs {
    padding: 0;
    background-color: transparent;
  }
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.11/clipboard.min.js"></script>
{% endblock %}

<!---->
{% block breadcrumbs %}
<li>
  <a href="{% url 'ui:course' module.get_parent.slug %}">
    <i data-lucide="home" class="size-4"></i>
    <span>{% trans 'Home' %}</span>
  </a>
</li>
<li>
  <a href="{% url 'ui:module' module.get_parent.slug module.slug %}">
    <i data-lucide="book" class="size-4"></i>
    <span>{{ module }}</span>
  </a>
</li>
<li>
  <a
    href="{% url 'ui:lesson' module.get_parent.slug module.slug item.get_parent.slug %}"
  >
    <i data-lucide="presentation" class="size-4"></i>
    <span>{{ item.get_parent }}</span>
  </a>
</li>
<li>
  <span>
    {% if item.type %}
    <i data-lucide="play-circle" class="size-4"></i>
    {% else %}
    <i data-lucide="book-text" class="size-4"></i>
    {% endif %}
    <span>{{ item }}</span>
  </span>
</li>
{% endblock %}

<!---->
{% block course_content %}
<div
  class="prose mx-auto prose-sm prose-video:rounded-box xl:prose-lg 2xl:prose-xl prose-headings:text-primary prose-headings:font-serif rtl:prose-headings:font-kufi prose-img:rounded-box prose-img:w-full prose-pre:bg-base-200 prose-pre:border prose-pre:border-base-300 prose-pre:bg-base-200 prose-pre:border prose-pre:border-base-300"
>
  <h1>{{ item }}</h1>
  {{ item.content }}
</div>

<script>
  const x = new ClipboardJS(".btn-copy");
</script>
{% endblock %}

how/ui/templates/ui/learn/content/lesson.html
{% extends 'ui/learn/base.html' %}{% load i18n wagtailcore_tags %}

<!---->
{% block title %}{{ block.super }} | {{ lesson.title }}{% endblock %}

<!---->
{% block course_title %}{{ lesson }}{% endblock %}

<!---->
{% block breadcrumbs %}
<li>
  <a href="{% url 'ui:course' module.get_parent.slug %}">
    <i data-lucide="home" class="size-4"></i>
    <span>{% trans 'Home' %}</span>
  </a>
</li>
<li>
  <a href="{% url 'ui:module' module.get_parent.slug module.slug %}">
    <i data-lucide="book" class="size-4"></i>
    <span>{{ module }}</span>
  </a>
</li>
<li>
  <span>
    <i data-lucide="presentation" class="size-4"></i>
    <span>{{ lesson }}</span>
  </span>
</li>
{% endblock %}

<!---->
{% block course_content %}
<div
  class="prose mx-auto prose-sm prose-video:rounded-box xl:prose-lg 2xl:prose-xl prose-headings:text-primary prose-headings:font-serif rtl:prose-headings:font-kufi prose-img:rounded-box prose-img:w-full prose-pre:bg-base-200 prose-pre:border prose-pre:border-base-300"
>
  <h1>{{ lesson }}</h1>
  {{ lesson.description|richtext }}
</div>
{% endblock %}

<!---->
{% block drawer_title %}{{ lesson }}{% endblock %}

<!---->
{% block drawer_content %}
<li>
  <a
    href="{% url 'ui:course' module.get_parent.slug %}"
    class="btn btn-sm btn-soft btn-primary md:btn-md btn-block 2xl:btn-xl justify-start"
  >
    <i data-lucide="home" class="size-4 md:size-6 xl:size-7 2xl:size-8"></i>
    <span>{% trans 'Home' %}</span>
  </a>
</li>
<li>
  <a
    href="{% url 'ui:module' module.get_parent.slug module.slug %}"
    class="btn btn-sm btn-soft btn-primary md:btn-md btn-block 2xl:btn-xl justify-start"
  >
    <i data-lucide="book" class="size-4 md:size-6 xl:size-7 2xl:size-8"></i>
    <span>{{ module }}</span>
  </a>
</li>
<li>
  <div class="rounded-field collapse w-full">
    <input id="lesson-{{ lesson.id }}" type="checkbox" class="hidden" />

    <label
      for="lesson-{{ lesson.id }}"
      class="collapse-title btn btn-sm btn-soft btn-primary md:btn-md btn-block 2xl:btn-xl justify-between p-4"
    >
      <span class="flex items-center gap-[inherit]">
        <i
          data-lucide="book-audio"
          class="size-4 md:size-6 xl:size-7 2xl:size-8"
        ></i>
        <span>{% trans 'Lesson Material' %}</span>
      </span>

      <i
        data-lucide="chevron-down"
        class="size-4 md:size-6 xl:size-7 2xl:size-8"
      ></i>
    </label>

    <div class="collapse-content">
      <ol class="grid gap-2">
        {% for item in lesson.get_children.specific %}
        <li>
          {% if item.content_type.name == 'item' %}
          <a
            href="{% url 'ui:item' module.get_parent.slug module.slug lesson.slug item.slug %}"
            class="btn btn-sm btn-soft btn-primary md:btn-md btn-block 2xl:btn-xl justify-start"
          >
            <i
              data-lucide="book-text"
              class="size-4 md:size-6 xl:size-7 2xl:size-8"
            ></i>
            <span>{{ item }}</span>
          </a>
          {% else %}
          <a
            href="{% url 'ui:assignment' module.get_parent.slug item.slug %}"
            class="btn btn-sm btn-soft btn-primary md:btn-md btn-block 2xl:btn-xl justify-start"
          >
            <i
              data-lucide="book-check"
              class="size-4 md:size-6 xl:size-7 2xl:size-8"
            ></i>
            <span>{{ item }}</span>
          </a>
          {% endif %}
        </li>
        {% endfor %}
      </ol>
    </div>
  </div>
</li>
{% endblock %}

how/ui/templates/ui/learn/content/module.html
{% extends 'ui/learn/base.html' %}{% load i18n wagtailcore_tags %}

<!---->
{% block title %}{{ block.super }} | {% trans 'Learn' %} | {{ module }}{% endblock %}

<!---->
{% block course_title %}{{ module }}{% endblock %}

<!---->
{% block breadcrumbs %}
<li>
  <a href="{% url 'ui:course' module.get_parent.slug %}">
    <i data-lucide="home" class="size-4"></i>
    <span>{% trans 'Home' %}</span>
  </a>
</li>
<li>
  <span>
    <i data-lucide="book" class="size-4"></i>
    <span>{{ module }}</span>
  </span>
</li>
{% endblock %}

<!---->
{% block course_content %}
<div
  class="prose mx-auto prose-sm prose-video:rounded-box xl:prose-lg 2xl:prose-xl prose-headings:text-primary prose-headings:font-serif rtl:prose-headings:font-kufi prose-img:rounded-box prose-img:w-full prose-pre:bg-base-200 prose-pre:border prose-pre:border-base-300"
>
  <h1>{{ module.title }}</h1>
  {{ module.description|richtext }}
</div>
{% endblock %}

<!---->
{% block drawer_title %}{{ module.title }}{% endblock %}

<!---->
{% block drawer_content %}
<li>
  <a
    href="{% url 'ui:course' module.get_parent.slug %}"
    class="btn btn-sm btn-soft btn-primary md:btn-md btn-block 2xl:btn-xl justify-start"
  >
    <i data-lucide="home" class="size-4 md:size-6 xl:size-7 2xl:size-8"></i>
    <span>{% trans 'Home' %}</span>
  </a>
</li>

<li>
  <div class="rounded-field collapse w-full">
    <input id="lessons" type="checkbox" class="hidden" />

    <label
      for="lessons"
      class="collapse-title btn btn-sm btn-soft btn-primary md:btn-md btn-block 2xl:btn-xl justify-between p-4"
    >
      <span class="flex items-center gap-[inherit]">
        <i
          data-lucide="presentation"
          class="size-4 md:size-6 xl:size-7 2xl:size-8"
        ></i>
        <span>{% trans 'Lessons' %}</span>
      </span>

      <i
        data-lucide="chevron-down"
        class="size-4 md:size-6 xl:size-7 2xl:size-8"
      ></i>
    </label>

    <div class="collapse-content">
      <ol class="grid gap-2">
        {% for lesson in module.get_children.specific %}
        <li>
          <div class="rounded-field collapse w-full">
            <input id="lesson-{{ lesson.id }}" type="checkbox" class="hidden" />

            <label
              for="lesson-{{ lesson.id }}"
              class="collapse-title btn btn-sm btn-soft btn-primary md:btn-md btn-block 2xl:btn-xl justify-between p-4"
            >
              <span>{{ lesson }}</span>

              <i
                data-lucide="chevron-down"
                class="size-4 md:size-6 xl:size-7 2xl:size-8"
              ></i>
            </label>

            <div class="collapse-content">
              <ol class="grid gap-2">
                {% for item in lesson.get_children.specific %}
                <li>
                  {% if item.content_type.name == 'item' %}
                  <a
                    href="{% url 'ui:item' module.get_parent.slug module.slug lesson.slug item.slug %}"
                    class="btn btn-sm btn-soft btn-primary md:btn-md btn-block 2xl:btn-xl justify-start"
                  >
                    <i
                      data-lucide="book-text"
                      class="size-4 md:size-6 xl:size-7 2xl:size-8"
                    ></i>
                    <span>{{ item }}</span>
                  </a>
                  {% else %}
                  <a
                    href="{% url 'ui:assignment' module.get_parent.slug item.slug %}"
                    class="btn btn-sm btn-soft btn-primary md:btn-md btn-block 2xl:btn-xl justify-start"
                  >
                    <i
                      data-lucide="book-check"
                      class="size-4 md:size-6 xl:size-7 2xl:size-8"
                    ></i>
                    <span>{{ item }}</span>
                  </a>
                  {% endif %}
                </li>
                {% endfor %}
              </ol>
            </div>
          </div>
        </li>
        {% endfor %}
      </ol>
    </div>
  </div>
</li>
{% endblock %}

how/ui/templates/ui/learn/content/submission.html
{% extends 'ui/learn/content/assignment.html' %}{% load i18n wagtailcore_tags %}

<!---->
{% block styles %}{{ block.super }}
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/github-dark.min.css"
/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/highlight.min.js"></script>
<script>
  hljs.highlightAll();
</script>
<style>
  pre code.hljs {
    padding: 0;
    background-color: transparent;
  }
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.11/clipboard.min.js"></script>
{% endblock %}

<!---->
{% block breadcrumbs %}{{ block.super }}
<li>
  <span>
    <i data-lucide="book-check" class="size-4"></i>
    <span>{{ submission }}</span>
  </span>
</li>
{% endblock %}

<!---->
{% block i_tab %}{% endblock %}
<!---->
{% block s_tab %}checked{% endblock %}
<!---->
{% block s_toggle %}checked{% endblock %}
<!---->
{% block s_btn %}{% endblock %}

<!---->
{% block assignment_content %}
<div class="carousel relative size-full">
  {% for question in assignment.questions.all %}
  <div class="carousel-item relative size-full flex-col overflow-y-auto pb-">
    <span class="absolute top-0 right-4 badge badge-info">
      {{ forloop.counter }} of {{ assignment.questions.count }}
    </span>

    <div class="flex flex-col gap-8 p-4">
      <div
        class="prose max-w-none prose-sm prose-video:rounded-box xl:prose-lg 2xl:prose-xl prose-headings:text-primary prose-headings:font-serif rtl:prose-headings:font-kufi prose-img:rounded-box prose-img:w-full prose-pre:bg-base-200 prose-pre:border prose-pre:border-base-300"
      >
        {{ question.text }}
      </div>

      <ol class="flex flex-col grow gap-4">
        {% for answer in question.answers.all %}
        <!---->
        {% if answer in submission.answers.all %}
        <li>
          {% if answer.is_correct %}
          <div
            class="card card-sm text-success border-1 border-success flex-row items-center gap-4 p-4 lg:card-md xl:card-lg 2xl:card-xl"
          >
            {% if question.type %}
            <input
              disabled
              checked
              type="checkbox"
              class="checkbox checkbox-sm checkbox-success lg:checkbox-md xl:checkbox-lg 2xl:checkbox-xl"
            />
            {% else %}
            <input
              disabled
              checked
              type="radio"
              class="radio radio-sm radio-success lg:radio-md xl:radio-lg 2xl:radio-xl"
            />
            {% endif %}

            <div
              class="prose max-w-none w-full grow text-inherit prose-sm prose-video:rounded-box xl:prose-lg 2xl:prose-xl prose-headings:text-primary prose-headings:font-serif rtl:prose-headings:font-kufi prose-img:rounded-box prose-img:w-full prose-pre:bg-base-200 prose-pre:border prose-pre:border-base-300"
            >
              {{ answer.text }}
            </div>
          </div>
          <div
            role="alert"
            class="alert alert-horizontal alert-success alert-soft"
          >
            <i
              data-lucide="check-circle2"
              class="size-4 md:size-6 xl:size-7 2xl:size-8"
            ></i>
            <strong class="sr-only">{% trans 'Correct' %}</strong>

            <div
              class="prose max-w-none w-full grow text-inherit prose-sm prose-video:rounded-box xl:prose-lg 2xl:prose-xl prose-headings:text-primary prose-headings:font-serif rtl:prose-headings:font-kufi prose-img:rounded-box prose-img:w-full prose-pre:bg-base-200 prose-pre:border prose-pre:border-base-300"
            >
              {{ answer.feedback|richtext }}
            </div>
          </div>
          {% else %}
          <div
            class="card card-sm text-error border-1 border-error flex-row items-center gap-4 p-4 lg:card-md xl:card-lg 2xl:card-xl"
          >
            {% if question.type %}
            <input
              disabled
              checked
              type="checkbox"
              class="checkbox checkbox-sm checkbox-error lg:checkbox-md xl:checkbox-lg 2xl:checkbox-xl"
            />
            {% else %}
            <input
              disabled
              checked
              type="radio"
              class="radio radio-sm radio-error lg:radio-md xl:radio-lg 2xl:radio-xl"
            />
            {% endif %}

            <div
              class="prose max-w-none w-full grow text-inherit prose-sm prose-video:rounded-box xl:prose-lg 2xl:prose-xl prose-headings:text-primary prose-headings:font-serif rtl:prose-headings:font-kufi prose-img:rounded-box prose-img:w-full prose-pre:bg-base-200 prose-pre:border prose-pre:border-base-300"
            >
              {{ answer.text }}
            </div>
          </div>
          <div
            role="alert"
            class="alert alert-horizontal alert-error alert-soft"
          >
            <i
              data-lucide="x-circle"
              class="size-4 md:size-6 xl:size-7 2xl:size-8"
            ></i>
            <strong class="sr-only">{% trans 'Incorrect' %}</strong>

            <div
              class="prose max-w-none w-full grow text-inherit prose-sm prose-video:rounded-box xl:prose-lg 2xl:prose-xl prose-headings:text-primary prose-headings:font-serif rtl:prose-headings:font-kufi prose-img:rounded-box prose-img:w-full prose-pre:bg-base-200 prose-pre:border prose-pre:border-base-300"
            >
              {{ answer.feedback|richtext }}
            </div>
          </div>
          {% endif %}
        </li>
        {% else %}
        <li>
          <div
            class="card card-sm text-primary border-1 border-transparent flex-row items-center gap-4 p-4 lg:card-md xl:card-lg 2xl:card-xl"
          >
            {% if question.type %}
            <input
              disabled
              type="checkbox"
              class="checkbox checkbox-sm checkbox-primary lg:checkbox-md xl:checkbox-lg 2xl:checkbox-xl"
            />
            {% else %}
            <input
              disabled
              type="radio"
              class="radio radio-sm radio-primary lg:radio-md xl:radio-lg 2xl:radio-xl"
            />
            {% endif %}

            <div
              class="prose max-w-none w-full grow text-inherit prose-sm prose-video:rounded-box xl:prose-lg 2xl:prose-xl prose-headings:text-primary prose-headings:font-serif rtl:prose-headings:font-kufi prose-img:rounded-box prose-img:w-full prose-pre:bg-base-200 prose-pre:border prose-pre:border-base-300"
            >
              {{ answer.text }}
            </div>
          </div>
        </li>
        {% endif %}
        <!---->
        {% endfor %}
      </ol>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}